spring.jpa.database=postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/alfian
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
security.jwt.enabled=true

server.port = 9090
spring.application.name = test
BASEURL=http://localhost:9090/api
server.servlet.context-path=/api

expired.token.password.minute=1200